plugin:
    name: 'rdarcy.albums::lang.plugin.name'
    description: 'rdarcy.albums::lang.plugin.description'
    author: 'Robin D''Arcy'
    icon: oc-icon-music
    homepage: ''
navigation:
    main-menu-item:
        label: Albums
        url: rdarcy/albums/albums
        icon: icon-music
