title: Albums
modelClass: RDArcy\Albums\Models\Album
list: $/rdarcy/albums/models/album/columns.yaml
recordUrl: 'rdarcy/albums/albums/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
