name: Albums
modelClass: RDArcy\Albums\Models\Album
form: $/rdarcy/albums/models/album/fields.yaml
defaultRedirect: rdarcy/albums/albums
create:
    redirect: 'rdarcy/albums/albums/update/:id'
    redirectClose: rdarcy/albums/albums
update:
    redirect: rdarcy/albums/albums
    redirectClose: rdarcy/albums/albums
preview: {  }
